### ISSUE TITLE
Add 'Internet connection' requirement

### ISSUE THREAD

**Issue by ps-nsk** [alexnsl/hwswa2#166]
Add **'Internet connection'** requirement. This is especially required for hosts in backnet. Without Internet connection (or at least proxy) you will not even install OA agent on a host.

**Comment by ps-nsk** [comment]
Verify at least connection to OA repo.

**Comment by alexnsl** [comment]
There is a yum repos availability check:

  yum_repos: which yum >/dev/null
             && echo $(yum repolist | sed '/repo id/,$ !d' 
                    | sed -e '1 d' -e '$ d' | awk '{ print $1}' | xargs)
             || echo no yum

if there is no internet connection, it will fail. Is this enough? Or you need a separate one?

**Comment by gorilych** [comment]
there are plenty of FW rules in roles, including to external services. F.e.:

git/hwswa2$ cat roles/common.fw.yaml
..
  rules:
  - connect_with: { hosts: [ dns.resolvers ] }
    ports: 53
    protos: [tcp, udp]
  - connect_with: { hosts: [ ntp.servers ] }
    ports: 123
    protos: [udp]
  - connect_with: { hosts: [ yum.repos, windows.update ] }
    ports: 80,443

**Comment by ps-nsk** [comment]
To Alexey: Add a check for connect to the OA repo (download.automation.odin.com). General system repos are not enough.

**Comment by ps-nsk** [comment]
I mean, general system repos can be available, while OA repo isn't.

**Comment by gorilych** [comment]
It's in FW rules as well:

~/git/hwswa2$ grep download.a roles/* | grep connect
roles/balinfe.yaml:  connect_with: { hosts: [download.automation.odin.com,
rev-reports.odin.com, report.odin.com] }
roles/balinos.yaml:  connect_with: { hosts: [ download.automation.odin.com
] }
roles/mn.fw.yaml:  connect_with: {hosts: [download.automation.odin.com]}
